# Config values related to balancer
balancer:
  targets: # List of targets between those load will be distributed.
    target_1: # Target name. Doesn't really matter. It can be used for debugging convenience, for example
      host: localhost # Target host
      port: 4001      # Target host
#    target_2:
#      host: target_2
#      port: 4002
#  ...
#  and go on
  balance_algorithm: 'round-robin' # Algorithm that balancer should to use. Able to: 'random', 'round-robin'
