# Defaults
BALANCER_DEFAULT_BUFFER_SIZE = 8192
BALANCER_DEFAULT_LISTENER_HOST = "0.0.0.0"
BALANCER_DEFAULT_LISTENER_PORT = 3333

BALANCER_DEFAULT_MAX_CONNECTIONS = 21
BALANCER_DEFAULT_CLEANUP_WAITING = 2  # seconds
BALANCER_DEFAULT_BIND_RETRY_WAITING = 5  # seconds
BALANCE_DEFAULT_GRACEFUL_SHUTDOWN_TIME = 5  # seconds
